"""Prometheus metrics for the Medical Triage API."""

from prometheus_client import Counter, Histogram

HTTP_REQUESTS_TOTAL = Counter(
    "medical_triage_http_requests_total",
    "Total number of HTTP requests.",
    ["method", "endpoint", "status"],
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "medical_triage_http_request_duration_seconds",
    "HTTP request duration in seconds.",
    ["method", "endpoint"],
)

PREDICTIONS_TOTAL = Counter(
    "medical_triage_predictions_total",
    "Total number of predictions generated by the model.",
    ["label_name"],
)
