"""Application use cases for medical text classification."""

from medical_triage.domain.entities import ClassificationResult
from medical_triage.domain.ports import ClassifierPort


class ClassifyMedicalTextUseCase:
    """Coordinate the medical text classification process.

    The use case depends only on the ClassifierPort abstraction,
    following the Dependency Inversion Principle.
    """

    def __init__(self, classifier: ClassifierPort) -> None:
        """Initialize the classification use case.

        Args:
            classifier: Classifier implementation compatible with
                ClassifierPort.
        """
        self._classifier = classifier

    def execute(self, text: str) -> ClassificationResult:
        """Validate and classify a medical text.

        Args:
            text: Medical text submitted by the client.

        Returns:
            ClassificationResult generated by the classifier.

        Raises:
            ValueError: If the supplied text is empty or too short.
        """
        normalized_text = text.strip()

        if not normalized_text:
            raise ValueError("Medical text cannot be empty.")

        if len(normalized_text) < 20:
            raise ValueError("Medical text must contain at least 20 characters.")

        return self._classifier.predict(normalized_text)
